name: Docker Image CI

on:
  push:
    branches: ["feature/bump-up", "master"]
  pull_request:
    branches: [master]

jobs:
  commons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      #- name: Build the Docker image
      #  run: docker build -f ./images/commons/Dockerfile -t vscode-commons:$(date +%s) ./images/commons/.
      - id: build
        name: Push to GitHub Packages
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./images/commons/.
          tags: docker.pkg.github.com/nolte/vscode-devcontainers/commons
          outputs: type=docker,dest=/tmp/commons.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: commons
          path: /tmp/commons.tar

    outputs:
      digest: ${{ steps.build.outputs.digest }}

  devops:
    runs-on: ubuntu-latest
    needs: commons
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: commons
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/commons.tar

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./images/devops/.
          tags: docker.pkg.github.com/nolte/vscode-devcontainers/devops

  commonsgolang:
    runs-on: ubuntu-latest
    needs: commons
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: commons
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/commons.tar

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./images/commons-golang/.
          tags: docker.pkg.github.com/nolte/vscode-devcontainers/commons-golang
  # devgolang:
  #   runs-on: ubuntu-latest
  #   needs: commonsgolang
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Push to GitHub Packages
  #       uses: docker/build-push-action@v5.0.0
  #       with:
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #         registry: docker.pkg.github.com
  #         repository: nolte/vscode-devcontainers/golang
  #         dockerfile: ./images/dev-golang/Dockerfile
  #         path: ./images/dev-golang/.
  #         tag_with_ref: false
  #         add_git_labels: true
  #         tags: latest
  # devops:
  #   runs-on: ubuntu-latest
  #   needs: devgolang
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Push to GitHub Packages
  #       uses: docker/build-push-action@v5.0.0
  #       with:
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #         registry: docker.pkg.github.com
  #         repository: nolte/vscode-devcontainers/devops
  #         dockerfile: ./images/devops/Dockerfile
  #         path: ./images/devops/.
  #         tag_with_ref: false
  #         add_git_labels: true
  #         tags: latest
  # npm:
  #   runs-on: ubuntu-latest
  #   needs: devgolang
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Push to GitHub Packages
  #       uses: docker/build-push-action@v5.0.0
  #       with:
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #         registry: docker.pkg.github.com
  #         repository: nolte/vscode-devcontainers/npm
  #         dockerfile: ./images/npm/Dockerfile
  #         path: ./images/npm/.
  #         tag_with_ref: false
  #         add_git_labels: true
  #         tags: latest
  # python:
  #   runs-on: ubuntu-latest
  #   needs: devgolang
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Push to GitHub Packages
  #       uses: docker/build-push-action@v5.0.0
  #       with:
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #         registry: docker.pkg.github.com
  #         repository: nolte/vscode-devcontainers/python
  #         dockerfile: ./images/python/Dockerfile
  #         path: ./images/python/.
  #         tag_with_ref: false
  #         add_git_labels: true
  #         tags: latest
  # k8soperator:
  #   runs-on: ubuntu-latest
  #   needs: [devgolang, devops]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Push to GitHub Packages
  #       uses: docker/build-push-action@v5.0.0
  #       with:
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #         registry: docker.pkg.github.com
  #         repository: nolte/vscode-devcontainers/k8s-operator
  #         dockerfile: ./images/k8sOperator/Dockerfile
  #         path: ./images/k8sOperator/.
  #         tag_with_ref: false
  #         add_git_labels: true
  #         tags: latest
