name: Docker Image CI

on:
  push:
    branches: ["feature/bump-up", "master"]
  pull_request:
    branches: [master]

env:
  IMAGE_TAG: latest

jobs:
  commons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      #- name: Build the Docker image
      #  run: docker build -f ./images/commons/Dockerfile -t vscode-commons:$(date +%s) ./images/commons/.
      - id: build
        name: Push to GitHub Packages
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./images/commons/.
          tags: ghcr.io/nolte/vscode-devcontainers/commons:$IMAGE_TAG
          outputs: type=docker,dest=/tmp/commons.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: commons
          path: /tmp/commons.tar

    outputs:
      digest: ${{ steps.build.outputs.digest }}

  devops:
    runs-on: ubuntu-latest
    needs: commons
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: commons
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/commons.tar

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./images/devops/.
          tags: ghcr.io/nolte/vscode-devcontainers/devops:$IMAGE_TAG

  commonsgolang:
    runs-on: ubuntu-latest
    needs: commons
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: commons
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/commons.tar

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./images/commons-golang/.
          tags: ghcr.io/nolte/vscode-devcontainers/commons-golang:$IMAGE_TAG
          outputs: type=docker,dest=/tmp/commons-golang.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: commons-golang
          path: /tmp/commons-golang.tar

  python:
    runs-on: ubuntu-latest
    needs: commonsgolang
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: commons-golang
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/commons-golang.tar

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./images/python/.
          tags: ghcr.io/nolte/vscode-devcontainers/python:$IMAGE_TAG